import express from 'express';
import { uploadQuotation,getQuotation,getAllQuotation,acceptQuotation, rejectQuotation,rejectAllQuotation,deliveredQuotation} from '../controllers/quotation.controller.js';
const quotationRouter = express.Router();
quotationRouter.post("/uploadQuotation",uploadQuotation);
quotationRouter.get("/getQuotation",getQuotation);
quotationRouter.get("/getAllQuotation",getAllQuotation);
quotationRouter.get("/acceptQuotation",acceptQuotation);
quotationRouter.post('/acceptQuotation/:id', acceptQuotation);
quotationRouter.post('/rejectQuotation/:id', rejectQuotation);
quotationRouter.post('/rejectAllQuotation/:id', rejectAllQuotation);
quotationRouter.post('/deliveredQuotation/:id', deliveredQuotation);
export default quotationRouter;